# Generated by Django 5.2.8 on 2025-11-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('github', 'GitHub Actions'), ('jenkins', 'Jenkins'), ('codepipeline', 'AWS CodePipeline')], default='github', max_length=32)),
                ('workflow', models.CharField(blank=True, default='', max_length=128)),
                ('run_id', models.CharField(blank=True, default='', max_length=64)),
                ('run_attempt', models.CharField(blank=True, default='', max_length=16)),
                ('branch', models.CharField(blank=True, default='', max_length=128)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.FloatField(default=0.0)),
                ('lce', models.FloatField(default=0.0)),
                ('prt', models.FloatField(default=0.0)),
                ('smo', models.FloatField(default=0.0)),
                ('dept', models.FloatField(default=0.0)),
                ('clbc', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
