# Generated by Django 5.2.8 on 2025-11-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.FloatField(default=0.0)),
                ('lce', models.FloatField(default=0.0)),
                ('prt', models.FloatField(default=0.0)),
                ('smo', models.FloatField(default=0.0)),
                ('dept', models.FloatField(default=0.0)),
                ('clbc', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
