# Generated by Django 5.2.8 on 2025-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='metric',
            name='commit_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='metric',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metric',
            name='run_attempt',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='metric',
            name='run_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='metric',
            name='source',
            field=models.CharField(choices=[('github', 'GitHub Actions'), ('jenkins', 'Jenkins'), ('codepipeline', 'AWS CodePipeline')], default='github', max_length=32),
        ),
        migrations.AddField(
            model_name='metric',
            name='workflow',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
